### ISSUE TITLE
Index.ipynb displays incorrectly in docker container

### ISSUE THREAD

**Issue by Shotgunosine** [miykael/nipype_tutorial#115]
If you follow the instructions in the index container and load up the index.ipynb from that container, then the notebook doesn't display with the html hidden or the tables formatted correctly. Additionally, the links don't have the target set to "_blank" so clicking on them opens in the same tab. 

I think this is because the notebook opens with the `Python [default] ` kernel instead of `Python [conda env:neuro]`. I put together a quick PR switching the notebooks to have `Python [conda env:neuro]` as their default environment.

**Comment by miykael** [comment]
@Shotgunosine. I've tried many different ways to keep the html hidden, unfortunately, I was never able to do so. I've tried your approach but it didn't seem to work in my case. Applying the changes from https://github.com/miykael/nipype_tutorial/pull/116/files to `index.ipynb` leads to nicely formatted html without the source code even when you close and reopen the docker container?

One simple reason why we left the `Python [default]` kernel was so that users can open notebooks on their machines (without docker) and don't have to switch ther kernel (or get an error message that `conda_env:neuro` cannot be found).

**Comment by Shotgunosine** [comment]
Unfortunately, it doesn't display nicely the first time it's loaded, but if you run the cell, then it does display nicely when you're using the `conda_env:neuro` kernel. It doesn't seem to throw an error when I open the notebook outside the container where that environment doesn't exist.

**Comment by miykael** [comment]
That's strange because I get the following popup if I [download](https://github.com/miykael/nipype_tutorial/blob/16bb70f9534e72fa229f6e55d89d624c06891ca8/index.ipynb) the changed `index.ipynb` file from your commit and try to open it on my system, without using docker.

![kernel_error](https://user-images.githubusercontent.com/950321/46380081-471e4300-c6a1-11e8-863f-4bc40a58c696.png)

And when I change `"display_name": "Python 3"` and `"name": "python3"` at the end of the notebook it all works fine again. But this might also be very lickely something particular to my system. @djarecka, if you have time, could you test it on your system as well?

**Comment by Shotgunosine** [comment]
I may have an older version of Jupyter outside of the container that isn’t throwing the error. Would you be opposed to a sed hack in the dockerfile that replaces the lines in the notebooks to set the name and display name in the docker container but leave them alone in the repo?

**Comment by miykael** [comment]
That sounds like a very good plan. So, have the `Python 3` on github, but the `conda env:neuro` inside the docker image? :+1:

Do you want to set this up? The best approach is probably to add an `--run sed...` command just after copying the notebooks [here](https://github.com/miykael/nipype_tutorial/blob/master/generate.sh#L32) (the same also for the singularity setup).

**Comment by Shotgunosine** [comment]
Yeah, I’ll take care of it and update the PR sometime today.
