### ISSUE TITLE
introduction_dataset doesn't get anatomical used by introduction_quickstart

### ISSUE THREAD

**Issue by Shotgunosine** [miykael/nipype_tutorial#117]
It looks like the introduction_quickstart notebook is referring to an anatomical that isn't downloaded by datalad in the introduction_dataset notebook. I've submitted a short pr to download the anatomicals.

**Comment by Shotgunosine** [comment]
Sorry for leaving out an important detail, I was mounting in my own data directory as described in the docker introduction:
`docker run -it --rm -v /path/to/nipype_tutorial/:/home/neuro/nipype_tutorial -v /path/to/data/:/data -v /path/to/output/:/output -p 8888:8888 miykael/nipype_tutorial jupyter notebook`

If you've done that, then you run the bids & tutorial dataset notebook, then you try to run any of the quickstarts, you find that you don't have the anats.

**Comment by miykael** [comment]
Ah, now I see. Yes, that's true. This is because `-v /path/to/data/:/data` will overwrite any tutorial data from the docker image with your own dataset. In this case, you're right with your commit.

To reduce download time on `circleci`, could you restrict the download to just subject 1, i.e. change your line to `/data/ds000114/sub-01/ses-test/anat/*`? This should be enough for the tutorials otherwise, no?

**Comment by Shotgunosine** [comment]
I’ll do that
