### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by arokem** [miykael/nipype_tutorial#16]
The last cell of the `example_preprocessing` notebook tries to create a directory in `/output/workingdir/preproc`, which may run into permissions issues, depending on your setup. 

Seems to be the case using the `satra/nhw17` docker image.

**Comment by miykael** [comment]
I'm not sure which cell you mean. Isn't the last cell just plotting the outlier figure? Independent of this, I agree, that the current setup assumes that you have writing privileges on `/output` and other folders, which might not be the case in ``satra/nhw17``.

Is there an easy solution to solve this issue? I'm not sure if it can be solved by running docker image with 
the paths directly pointing to `/home/neuro`:

```bash
docker run -it --rm \
    -v /path/to/nipype_tutorial/:/home/neuro/tutorial \
    -v /path/to/data/:/home/neuro/data \
    -v /path/to/output/:/home/neuro/output \
    -p 8888:8888 satra/nih-workshop-2017:latest jupyter notebook
```

For the moment, I would like to stay with ``satra/nih-workshop-2017``, because this image only takes 10.9GB, while ``satra/nhw17`` takes currently 23.5GB.

**Comment by arokem** [comment]
Looks like this can be resolved by adding a `/output` directory to the
image and chown/chmod'ing it.

See changes in https://github.com/neurohackweek/jupyterhub-docker/pull/4

Closing!
