### ISSUE TITLE
binder not working 

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#48]
Have no idea if this is the problems are temporary or not, but getting an error:
```
Found built image, launching...
Launching server...
Image gcr.io/binder-prod/r2d-fd74043miykael-nipype-tutorial:fe288ec45c588d5803f4fa2d77c4a85c72de7547 for user miykael-nipype_tutorial-pjzo5kg5 took too long to launch
```

have to check later

**Comment by miykael** [comment]
@djarecka - I've tried to use mybinder with the first version of the nipype_tutorial, but it always crashed with "took too long to launch". Back then the problem was that mybinder had to create the docker container from scratch instead of using "djarecka/niyppe_tutorial".

But also in general, I'm not sure if our docker image is just too big for mybinder. We perhaps could create a light version of the docker image, with only 1 subject and even less interfaces?

**Comment by djarecka** [comment]
I guess we could create a lither version (and assumed that people don't run `example_*`. I haven't done because it was working and it was creating a container from the Dockerfile included in the repo. I'm not sure when it stopped working, haven't tried for longer time...

**Comment by djarecka** [comment]
It's working now: https://hub.mybinder.org/user/miykael-nipype_tutorial-sk0z8uba/tree

Let's observe the mybinder issues. I believe once they build container it should work. But when we change something we should try to open mybinder, so it builds the container.

**Comment by djarecka** [comment]
closing the issue for now, we can reopen if needed
