### ISSUE TITLE
circleci error - Unable to find image 'djarecka/nipype_tutorial:master' locally

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#49]
@djarecka - I'm not familiar with the circleci's `config.yml` file but I got the following error: https://circleci.com/gh/miykael/nipype_tutorial/10

```bash
docker run -it --rm djarecka/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s 
Error: Unable to find image 'djarecka/nipype_tutorial:master' locally
```

Could it be that `$CIRCLE_BRANCH` should be replaced with `latest` in [config.yml#L15](https://github.com/miykael/nipype_tutorial/blob/master/.circleci/config.yml#L15) and [config.yml#L21](https://github.com/miykael/nipype_tutorial/blob/master/.circleci/config.yml#L21)?

**Comment by djarecka** [comment]
This is because the image was not built properly, you had some DataLad error (complained that git was not configured). I', trying to rebuild and see if it works. It could be that there is a new version of DataLad

**Comment by djarecka** [comment]
I got again the same error, will try to check with DataLad if this is intended.

**Comment by miykael** [comment]
@djarecka, thanks! Sorry, for my reduced activity. I'm co-organizing a [3-day neuroimaging workshop](https://github.com/miykael/workshops/tree/master/180309_marburg) next weekend. After this, I will refocus again on the tutorial.

**Comment by djarecka** [comment]
Nice! Were you planning to use mybinder?

**Comment by djarecka** [comment]
Voila! It actually works now: https://hub.mybinder.org/user/miykael-nipype_tutorial-sk0z8uba/tree

**Comment by miykael** [comment]
I wasn't planing on using mybinder, I created a docker image that is based on djarecka/nipype_tutorial.
But having a working mybinder would be perfect as a backup for people with docker issues.

The mybinder link above (https://hub.mybinder.org/user/miykael-nipype_tutorial-sk0z8uba/tree), now leads to a 404 page. [mybinder.org's FAQ](http://mybinder.readthedocs.io/en/latest/faq.html#how-long-will-my-binder-session-last) mentions that a session is closed after 10min of inactivity, but I didn't find out for how long they keep a build.

Also, the FAQ mentions that the kernel restarts whenever more than 4GB of RAM are used. Perhaps it nonetheless would make sense to create a lightweight Dockerfile? Perhaps just with the conda environment, FSL and 1 subject?

And as a FIY, the maximum simultaneous user per repo is 100.

**Comment by djarecka** [comment]
re mybinder: that's true, [this link](https://mybinder.org/v2/gh/miykael/nipype_tutorial/master) should be used. I haven't read recently, but at the time I was working I read that you can get anything between 1 and 4gb, so that's why I added this sentence to the main page " Note, that Binder provides between 1G and 4G RAM memory, some notebooks from Workflow Examples might not work. All notebooks from Introduction and Basic Concepts parts should work."

We can probably create a light version, but how would you like to do it. Create a new repo with subset of notebooks? Mybinder works per repo (at least that how I used it).
Or maybe we can have a special smaller branch? I think mybinder allows for various branches.

We can also wait and see if people are using current version and if they're having problems. Let me know if the links works at least for you.

**Comment by djarecka** [comment]
regarding DataLad - Yarik confirmed that this is a "new feature" (https://github.com/datalad/datalad/issues/2272). I'd wait what DataLad Developers decide on this issue. Since, you're preparing the workshop next week, the repo should work, so I'm creating PR that uses older version of DataLad temporary.

**Comment by miykael** [comment]
The link works perfectly! So, cool! Yes, let's keep it this way and see how people react to it.
About a light version: Yes, you can specify which branch it should use to build. So that would have been an option. But if it works like this than all is good.

And good to know about the DataLad issue. I will actually see Michael Hanke (another DataLad developer) at the workshop. Thanks for making the temporary change for the workshop.

**Comment by djarecka** [comment]
I think this issue can be closed, I created new issues regarding side problems mentioned here.
